name: sars-cov-2_clustering
channels:
  - https://software.repos.intel.com/python/conda/
  - conda-forge
dependencies:
  - python <3.11
  - scikit-learn-intelex
  - scikit-learn 
  - numpy
  - pandas
  - matplotlib
  - boruta_py
  - kmodes
  - tqdm
